#deployApp(appName = "MRportal", account = "pdgenetics", appFileManifest = "appFileManifest.txt")
library(shiny)
library(forestplot)
library(dplyr)
library(Cairo)
library(shinydashboard)
library(data.table)
library(xtable)
library(shinyBS)
library(shinyLP)
library(shinyjs)
library(shinyanimate)
library(ggplot2)
options(xtable.floating = T)
options(xtable.timestamp = "")

#============initial GWAS list
gwasList <- fread("initialgwasList.csv", sep = "#")
presnplist <- fread("www/dataResultsTable-res.csv")
warning.List <- fread("www/warning.List.csv")

source("custom.functions.R", local = T)
